[theme]
primaryColor = "#176B64"
backgroundColor = "#F6F8F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18292F"
font = "sans-serif"

[server]
address = "127.0.0.1"
maxUploadSize = 200

[browser]
gatherUsageStats = false
